name: consulta_cep_dio
description: Aplicativo de consulta de CEPs para o bootcamp Santander 2023 da DIO
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^7.0.0
  dio: ^5.3.3
  provider: ^6.0.5
  google_fonts: ^4.0.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env